apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gcp-secrets-manager-example
spec:
  backendType: gcpSecretsManager
  projectId: aeriscom-ab-dev-201907-2
  data:
    - key: hello-service-password
      name: password
      property: value
      version: 1